# ===== Database Configuration (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=123456a@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===== Branch Information =====
app.branch-name=Nha Thuoc So 1
app.hotline=1900xxxx